language: java

install: echo "I trust Maven."

# don't just run the tests, also run Findbugs and friends
script: mvn verify cobertura:cobertura coveralls:cobertura

jdk:
  - oraclejdk7

env:
  global:
    - secure: "SOvackQnVqleOnlj3ZerEK/FZUKhK9bqpH7+JD8zQ+BXysfnsKbRcu9mTJ2lr9dExZYkoQ94sRUmD8vOvGARMUeHEu5gqrwNc3GmSnq6HzeF0rTkBU16aY775TYVkd8TiiAaGz17/LqWv74Ugb4lfOQXGjV69xGO1PanM6EW2R0="

notifications:
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email:
    recipients:
      - mrnoname@naver.com