language: java

install: echo "I trust Maven."

# don't just run the tests, also run Findbugs and friends
script: mvn verify cobertura:cobertura coveralls:cobertura

jdk:
  - oraclejdk7

env:
  global:
    - secure: "WCo8544ObxLhUAvgNHScfvJkaCOHuyL8XThkIe9z7WmLcheSi5UBGbrEVo/2lOg4uwXND/Fe37g5MlBFDabhO0ta/BPG9pCuiSdL3W/LzvAt/5jx4AMIigiPvuiTKi/jptaGd7iGLOC02xs4NYL3BwseTc+bxTU0FP7sXStH+0c="

notifications:
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email:
    recipients:
      - mrnoname@naver.com
